version: '3'
services:
  docker-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-websocket-spoter
    container_name: docker-websocket
    #restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./servidroJS:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - docker-websocket-network
networks:
  docker-websocket-network:
